

const courtHouseList = [ 
    // 'Alhambra Courthouse',
    'Airport Courthouse',
    'Catalina Courthouse',
    'Bellflower Courthouse',
    'Beverly Hills Courthouse',
    'Burbank Courthouse',
    'Chatsworth Courthouse',
    'Compton Courthouse',
    'Downey Courthouse',
    'East Los Angeles Courthouse',
    'El Monte Courthouse',
    'Glendale Courthouse',
   ' Governor George Deukmejian Courthouse', 
    'Hollywood Courthouse',
    'Huntington Park Courthouse',
    'Inglewood Courthouse',
    'Long Beach Courthouse',
    'Malibu Courthouse',
    'Metropolitan Courthouse,', 
    'Michael D. Antonovich Antelope Valley Courthouse, Lancaster',
    'Norwalk Courthouse',
    'Pasadena Courthouse',
    'Pomona Courthouse North',
    'Pomona Courthouse South',
    'Redondo Beach Courthouse',
    'San Fernando Courthouse',
    'San Pedro Courthouse',
    'San Pedro Courthouse Annex',
    'Santa Clarita Courthouse',
    'Santa Monica Courthouse',
    'Spring Street Courthouse',
    'Stanley Mosk Courthouse', 
   ' Torrance Courthouse',
    'Van Nuys Courthouse East',
   ' Van Nuys Courthouse West',
    'West Covina Courthouse',
    'West Los Angeles Courthouse',
    'Whittier Courthouse',
    'Bellflower Courthouse',
    'Chatsworth Courthouse',
   'Compton Courthouse',
    'Inglewood Courthouse',
    'Pasadena Courthouse',
    'Santa Monica Courthouse',
] 



export default courtHouseList ;